### ISSUE TITLE
如何配置主题文件？

### ISSUE THREAD

**Issue by yihuishou** [giuem/hexo-theme-iris#4]
Hexo 3.8.0 按照说明修改了 Hexo 主题文件

错误信息：

```
Unhandled rejection TypeError: C:\Users\SH\blog\themes\iris\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html <% if(config.language) { %>lang="<%- config.language %>"<% } %>>
 >> 3|   <%- partial('_head/index') %>
    4|   <body>
    5|     <%- partial("_partial/header") %>
    6|     <main class="main">

C:\Users\SH\blog\themes\iris\layout\_head\index.ejs:51
    49|   <%- partial("dns-prefetch", {}, {cache: true}) %>
    50|   <%- partial("favicon", {}, {cache: true}) %>
 >> 51|   <%- partial("rss", {}, {cache: true}) %>
    52|   <%- partial("open-graph", {meta}) %>
    53|   <%- partial("custom", {}, {cache: true}) %>
    54| 

C:\Users\SH\blog\themes\iris\layout\_head\rss.ejs:2
    1| <% if(theme.head.rss) { %>
 >> 2|   <% if(config.feed.type == "atom"){ %>
    3|     <link rel="alternate" type="application/atom+xml" href="<%= theme.head.rss || '#' %>">
    4|   <% } else if(config.feed.type == "rss2") { %>
    5|     <link rel="alternate" type="application/rss+xml" href="<%= theme.head.rss || '#' %>">

Cannot read property 'type' of undefined
    at eval (eval at compile (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:23)
    at returnedFn (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:69:17)
    at returnedFn (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:18:17)
    at returnedFn (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (C:\Users\SH\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:694:18)

Unhandled rejection TypeError: C:\Users\SH\blog\themes\iris\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html <% if(config.language) { %>lang="<%- config.language %>"<% } %>>
 >> 3|   <%- partial('_head/index') %>
    4|   <body>
    5|     <%- partial("_partial/header") %>
    6|     <main class="main">

C:\Users\SH\blog\themes\iris\layout\_head\index.ejs:51
    49|   <%- partial("dns-prefetch", {}, {cache: true}) %>
    50|   <%- partial("favicon", {}, {cache: true}) %>
 >> 51|   <%- partial("rss", {}, {cache: true}) %>
    52|   <%- partial("open-graph", {meta}) %>
    53|   <%- partial("custom", {}, {cache: true}) %>
    54| 

C:\Users\SH\blog\themes\iris\layout\_head\rss.ejs:2
    1| <% if(theme.head.rss) { %>
 >> 2|   <% if(config.feed.type == "atom"){ %>
    3|     <link rel="alternate" type="application/atom+xml" href="<%= theme.head.rss || '#' %>">
    4|   <% } else if(config.feed.type == "rss2") { %>
    5|     <link rel="alternate" type="application/rss+xml" href="<%= theme.head.rss || '#' %>">

Cannot read property 'type' of undefined
    at eval (eval at compile (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:23)
    at returnedFn (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:69:17)
    at returnedFn (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (C:\Users\SH\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:18:17)
    at returnedFn (C:\Users\SH\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (C:\Users\SH\blog\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (C:\Users\SH\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\SH\blog\node_modules\bluebird\js\release\promise.js:694:18)
```

**Comment by giuem** [comment]
如果要开启 RSS，请配合 https://github.com/hexojs/hexo-generator-feed 这个插件
